---

- name: Upload replay
  copy:
    src: ../../{{ file_name }}
    dest: /tmp/data.log

- name: Call oneshot import
  uri:
    url: https://localhost:8089/services/data/inputs/oneshot
    validate_certs: no
    method: POST
    user: admin
    password: "{{ attack_range_password }}"
    force_basic_auth: yes
    body_format: form-urlencoded
    body:
      name: /tmp/data.log
      sourcetype: "{{ sourcetype }}"
      rename-source: "{{ source }}"
      index: "{{ index }}"
    status_code: 201