---

- include: install_sysmon_linux.yml
- include: configure_inputs.yml

- name: Restart splunk uf
  become: true
  command: "systemctl restart SplunkForwarder"
  when: cloud_provider != "local"

- name: Restart splunk uf
  become: true
  command: "/opt/splunkforwarder/bin/splunk restart"
  when: cloud_provider == "local"