---

- name: change password splunk
  shell: '/opt/splunk/bin/splunk edit user admin -password {{ attack_range_password }} -auth admin:Pl3ase-k1Ll-me:p'
  become: yes
  become_user: splunk

- name: restart splunk
  service: name=splunk state=restarted
  become: yes