---

- name: change password splunk
  shell: '/opt/splunkforwarder/bin/splunk edit user admin -password {{ attack_range_password }} -auth admin:Pl3ase-k1Ll-me:p'
  become: yes
  ignore_errors: yes

- name: Change hostname
  shell: '/opt/splunkforwarder/bin/splunk set default-hostname {{ hostname }} -auth admin:{{ attack_range_password }}'
  become: yes

- name: Change servername
  shell: '/opt/splunkforwarder/bin/splunk set servername {{ hostname }} -auth admin:{{ attack_range_password }}'
  become: yes

- name: Restart splunk uf
  become: true
  command: "systemctl restart SplunkForwarder"
  when: cloud_provider != "local"

- name: Restart splunk uf
  become: true
  command: "/opt/splunkforwarder/bin/splunk restart"
  when: cloud_provider == "local"