---
- name: check if c:\BadBlood dir exist
  win_stat:
    path: 'C:\BadBlood'
  register: badblood_path
  tags:
   - badblood


- name: Git clone BadBlood
  win_shell: git clone https://github.com/davidprowe/BadBlood.git C:\BadBlood
  when: windows_domain_controller_run_badblood == "1" and badblood_path.stat.exists == false
  tags:
   - badblood

