
- include: create.yml
  when: join_domain == "1" and cloud_provider != "local"

- include: create_local.yml
  when: join_domain == "1" and cloud_provider == "local"

- include: windows-disable-firewall.yml
  when: join_domain == "1"