---
#- include: install_deb_uf.yml
#- include: configure_outputs_conf.yml
- include: nginx_web_proxy.yml
#- include: create_deploymentclient.yml
- include: configure_inputs.yml

- name: Restart splunk uf
  become: true
  command: "systemctl restart SplunkForwarder"

- name: restart nginx again
  become: true
  command: "nginx -s reload"
