---

- name: copy default.conf to add the proxy information 
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  when: proxy_server_ip != "10.0.1.12" or proxy_server_port != "8000"

- name: reload nginx
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
  when: proxy_server_ip != "10.0.1.12" or proxy_server_port != "8000"