- hosts: all
  gather_facts: False
  become: true
  roles:
    - role: set_hostname_linux
    - role: linux_server_post
      when: install_contentctl == "0"
    - role: update_sysmon_config_linux
      when: install_contentctl == "0"
    - role: linux_agent_prelude
      when: install_contentctl == "0"
    - role: splunk_byo_linux
      when: install_contentctl == "0"
    - role: contentctl
      when: install_contentctl == "1"