---

- name: Install Atomic Red Team
  become: true
  shell: |
    pwsh -Command 'IEX (IWR https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicsfolder.ps1 -UseBasicParsing); 
    Install-AtomicsFolder -Force; 
    IEX (IWR https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1); 
    Install-AtomicRedTeam -Force'
  register: output_art

- debug:
    var: output_art.stdout_lines