- name: Create local folder directory
  file:
    path: "{{ item }}"
    state: directory
    owner: splunk
    group: splunk
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/DA-ESS-ContentUpdate/local/

